### ISSUE TITLE
need some files to example this solution

### ISSUE THREAD

**Issue by ghost** [jmbrito01/VM-CrackMe#1]
```
    Data = make_shared<VMData>("C:\\Users\\jmbri\\data.stub");
    Exports = make_shared<VMFunctions>("C:\\Users\\jmbri\\export.stub");
    VMRegs Regs = {0};
    Parser = make_shared<VMParser>("C:\\Users\\jmbri\\final_code.stub", Data, Exports);
```

**Comment by ghost** [comment]
ups sorry 
I haven't seen the project code virt

**Comment by ghost** [comment]
it is sln for orleans product, @jmbrito01 ?

**Comment by jmbrito01** [comment]
This is not for oreans products (such as themida), this is a simple approach to prove the concept of virtualization.

**Comment by ghost** [comment]
@jmbrito01 i am try run CodeVirtualizer for generate stub's (exe example) and this doesn't work. :c 
files generates with 0kb size

**Comment by jmbrito01** [comment]
No errors occurred during the process? @brainblowjob

**Comment by ghost** [comment]
@jmbrito01 Nope
